03/19/2024 21:10:13 - INFO - __main__ - ***** Running training *****
03/19/2024 21:10:13 - INFO - __main__ -   Num examples = 11647
03/19/2024 21:10:13 - INFO - __main__ -   Num batches each epoch = 2912
03/19/2024 21:10:13 - INFO - __main__ -   Num Epochs = 1
03/19/2024 21:10:13 - INFO - __main__ -   Instantaneous batch size per device = 4
03/19/2024 21:10:13 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
03/19/2024 21:10:13 - INFO - __main__ -   Gradient Accumulation steps = 1
03/19/2024 21:10:13 - INFO - __main__ -   Total optimization steps = 2912
Steps:   0%|                                                                                                                                                                            | 0/2912 [00:00<?, ?it/s]/home/dwang/miniconda3/envs/ootd/lib/python3.10/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(
Caption File does not exist.
Caption File does not exist.
Caption File does not exist.
Caption File does not exist.
Caption File does not exist.
Caption File does not exist.
Caption File does not exist.
Caption File does not exist.
Steps:   0%|                                                                                                                                                                  | 1/2912 [00:05<4:08:56,  5.13s/it]03/19/2024 21:10:18 - INFO - __main__ - Running validation...
{'image_encoder', 'requires_safety_checker', 'controlnet'} was not found in config. Values will be initialized to default values.
                                                                                                                                                                                                                 {'timestep_spacing', 'prediction_type'} was not found in config. Values will be initialized to default values.
Loaded scheduler as PNDMScheduler from `scheduler` subfolder of runwayml/stable-diffusion-v1-5.                                                                                            | 0/6 [00:00<?, ?it/s]
Loaded feature_extractor as CLIPImageProcessor from `feature_extractor` subfolder of runwayml/stable-diffusion-v1-5.
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 1117.14it/s]
03/19/2024 21:10:19 - WARNING - pipeline.pipeline_controlnet - You have disabled the safety checker for <class 'pipeline.pipeline_controlnet.StableDiffusionControlNetPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
{'disable_corrector', 'solver_order', 'use_karras_sigmas', 'sample_max_value', 'predict_x0', 'solver_p', 'solver_type', 'timestep_spacing', 'thresholding', 'lower_order_final', 'prediction_type', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
Traceback (most recent call last):
  File "/opt/disk1/dwang/sci/DVTON/OOTDiffusion/controlnet/train_controlnet.py", line 1364, in <module>
    main(args)
  File "/opt/disk1/dwang/sci/DVTON/OOTDiffusion/controlnet/train_controlnet.py", line 1320, in main
    image_logs = log_validation(
  File "/opt/disk1/dwang/sci/DVTON/OOTDiffusion/controlnet/train_controlnet.py", line 133, in log_validation
    with open(validation_image.replace(".jpg", "_keypoints.json")) as f:
FileNotFoundError: [Errno 2] No such file or directory: './00008_00_keypoints.json'